# Site settings
name: wyudong
description: wyudong's site
permalink: /blog/:title

# Sass
sass:
  style: compressed
  sass_dir: _sass

# Build settings
markdown: kramdown
exclude: [Gemfile, Gemfile.lock, README.md]

# Serve settings
port: 6280

# Output settings
timezone: Asia/Shanghai
